sonar.projectKey=colombo-labs_movicol-backend
sonar.organization=colombo-labs
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/*.spec.*
sonar.typescript.lcov.reportPaths=coverage/lcov.info
